import '@/styles/global.sass';

import { Inter } from 'next/font/google';

const interFont = Inter({
    variable: '--font-inter',
    display: 'swap',
    subsets: ['latin'],
    fallback: ['Arial', 'sans-serif']
});

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`relative bg-neutral-100 min-h-screen ${interFont.className}`}>
                {children}
            </body>
        </html>
    );
}
